# 150 cities with their safety status
CITY_SAFETY = {
    "paris": "Safe",
    "new york": "Neutral",
    "tokyo": "Safe",
    "mumbai": "Unsafe",
    "berlin": "Safe",
    "london": "Safe",
    "delhi": "Unsafe",
    "san francisco": "Neutral",
    "los angeles": "Neutral",
    "chicago": "Neutral",
    "sydney": "Safe",
    "melbourne": "Safe",
    "toronto": "Safe",
    "vancouver": "Safe",
    "beijing": "Unsafe",
    "shanghai": "Unsafe",
    "bangkok": "Neutral",
    "singapore": "Safe",
    "dubai": "Safe",
    "rome": "Safe",
    "madrid": "Safe",
    "barcelona": "Safe",
    "istanbul": "Neutral",
    "moscow": "Neutral",
    "rio de janeiro": "Unsafe",
    "cape town": "Unsafe",
    "jakarta": "Unsafe",
    "seoul": "Safe",
    "hong kong": "Safe",
    "amsterdam": "Safe",
    "brussels": "Safe",
    "vienna": "Safe",
    "prague": "Safe",
    "warsaw": "Safe",
    "lisbon": "Safe",
    "oslo": "Safe",
    "stockholm": "Safe",
    "helsinki": "Safe",
    "copenhagen": "Safe",
    "athens": "Neutral",
    "budapest": "Safe",
    "zurich": "Safe",
    "geneva": "Safe",
    "montreal": "Safe",
    "boston": "Neutral",
    "philadelphia": "Neutral",
    "washington": "Neutral",
    "seattle": "Safe",
    "portland": "Safe",
    "auckland": "Safe",
    "wellington": "Safe",
    "brisbane": "Safe",
    "adelaide": "Safe",
    "melaka": "Safe",
    "kuala lumpur": "Neutral",
    "manila": "Unsafe",
    "bangalore": "Unsafe",
    "kolkata": "Unsafe",
    "hyderabad": "Unsafe",
    "chennai": "Unsafe",
    "riyadh": "Safe",
    "jeddah": "Safe",
    "tehran": "Unsafe",
    "baghdad": "Unsafe",
    "dubrovnik": "Safe",
    "zagreb": "Safe",
    "belgrade": "Neutral",
    "sarajevo": "Neutral",
    "santiago": "Neutral",
    "buenos aires": "Unsafe",
    "quito": "Unsafe",
    "lima": "Unsafe",
    "bogota": "Unsafe",
    "caracas": "Unsafe",
    "havana": "Unsafe",
    "kingston": "Unsafe",
    "mexico city": "Unsafe",
    "guadalajara": "Unsafe",
    "montevideo": "Safe",
    "asuncion": "Neutral",
    "la paz": "Unsafe",
    "sucre": "Safe",
    "osaka": "Safe",
    "kyoto": "Safe",
    "nagoya": "Safe",
    "fukuoka": "Safe",
    "sapporo": "Safe",
    "hiroshima": "Safe",
    "new delhi": "Unsafe",
    "kolkata": "Unsafe",
    "chennai": "Unsafe",
    "bengaluru": "Unsafe",
    "hyderabad": "Unsafe",
    "jaipur": "Unsafe",
    "lucknow": "Unsafe",
    "pune": "Neutral",
    "ahmedabad": "Neutral",
    "surat": "Neutral",
    "karachi": "Unsafe",
    "lahore": "Unsafe",
    "islamabad": "Safe",
    "quetta": "Unsafe",
    "rawalpindi": "Unsafe",
    "cairo": "Unsafe",
    "alexandria": "Unsafe",
    "giza": "Unsafe",
    "casablanca": "Neutral",
    "marrakech": "Neutral",
    "tangier": "Neutral",
    "dakar": "Unsafe",
    "abidjan": "Unsafe",
    "lagos": "Unsafe",
    "accra": "Neutral",
    "nairobi": "Unsafe",
    "mombasa": "Unsafe",
    "kampala": "Unsafe",
    "dodoma": "Unsafe",
    "dar es salaam": "Neutral",
    "pretoria": "Unsafe",
    "johannesburg": "Unsafe",
    "durban": "Unsafe",
    "cape town": "Unsafe",
    "auckland": "Safe",
    "wellington": "Safe",
    "christchurch": "Safe",
    "hamilton": "Safe",
    "honolulu": "Safe",
    "los cabos": "Neutral",
    "cancun": "Neutral",
    "tijuana": "Unsafe",
    "vancouver": "Safe",
    "calgary": "Safe",
    "edmonton": "Safe",
    "montreal": "Safe",
    "ottawa": "Safe",
    "toronto": "Safe",
    "boston": "Neutral",
    "newark": "Neutral",
    "philadelphia": "Neutral",
    "washington": "Neutral",
    "miami": "Neutral",
    "orlando": "Neutral",
    "las vegas": "Neutral",
    "san diego": "Safe",
    "seattle": "Safe",
    "portland": "Safe",
    "denver": "Safe",
    "chicago": "Neutral",
    "houston": "Neutral",
    "atlanta": "Neutral",
    "dallas": "Neutral",
    "detroit": "Unsafe",
    "minneapolis": "Safe",
    "st. louis": "Neutral",
    "new orleans": "Unsafe",
    "phoenix": "Neutral",
    "san jose": "Safe",
    "san francisco": "Neutral"
}

def get_safety_status(city_name: str) -> str:
    """
    Return the safety status for a given city.
    If city is not in the dataset, return 'Unknown'.
    """
    return CITY_SAFETY.get(city_name.lower(), "Unknown")
